

enum SOCKS5Status {
	SOCKS5ERR_SUCCESS = 0,
	SOCKS5ERR_FAILURE = 1,
	SOCKS5ERR_CONNECTION_NOT_ALLOWED = 2,
	SOCKS5ERR_NETWORK_UNREACHABLE = 3,
	SOCKS5ERR_HOST_UNREACHABLE = 4,
	SOCKS5ERR_CONNECTION_REFUSED = 5,
	SOCKS5ERR_TTL_EXPIRED = 6,
	SOCKS5ERR_COMMAND_NOT_SUPPORTED = 7,
	SOCKS5ERR_ADDRESS_TYPE_NOT_SUPPORTED = 8,
	SOCKS5ERR_UNASSIGNED = 9
};


enum SOCKS5Authentication {
	SOCKS5AUTH_NO_AUTHENTICATION = 0,
	SOCKS5AUTH_GSSAPI = 1,
	SOCKS5AUTH_BASIC_AUTHENTICATION = 2,
	SOCKS5AUTH_IANA_ASSIGNED = 3,
	SOCKS5AUTH_RESERVED = 128,
	SOCKS5AUTH_NOT_ACCEPTABLE = 255
};
